// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 2
// RUN: %clang_cc1 -triple riscv64 -target-feature +xtheadvector \
// RUN:   -disable-O0-optnone -emit-llvm %s -o - | \
// RUN:   opt -S -passes=mem2reg | FileCheck %s

#include <riscv_vector.h>

// CHECK-LABEL: define dso_local <vscale x 8 x half> @load_f16m2_index8
// CHECK-SAME: (ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[INDEX:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x half> @llvm.riscv.th.vlxe.nxv8f16.nxv8i8.i64(<vscale x 8 x half> poison, ptr [[BASE]], <vscale x 8 x i8> [[INDEX]], i64 [[VL]])
// CHECK-NEXT:    ret <vscale x 8 x half> [[TMP0]]
//
vfloat16m2_t load_f16m2_index8(const _Float16 *base, vuint8m1_t index, size_t vl) {
  return __riscv_th_vloxei8_v_f16m2(base, index, vl);
}

// CHECK-LABEL: define dso_local <vscale x 8 x half> @load_f16m2_index8_masked
// CHECK-SAME: (<vscale x 8 x i1> [[MASK:%.*]], <vscale x 8 x half> [[MERGE:%.*]], ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[INDEX:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x half> @llvm.riscv.th.vlxe.mask.nxv8f16.nxv8i8.i64(<vscale x 8 x half> [[MERGE]], ptr [[BASE]], <vscale x 8 x i8> [[INDEX]], <vscale x 8 x i1> [[MASK]], i64 [[VL]])
// CHECK-NEXT:    ret <vscale x 8 x half> [[TMP0]]
//
vfloat16m2_t load_f16m2_index8_masked(vbool8_t mask, vfloat16m2_t merge, const _Float16 *base, vuint8m1_t index, size_t vl) {
  return __riscv_th_vloxei8_v_f16m2_mu(mask, merge, base, index, vl);
}

// CHECK-LABEL: define dso_local void @store_f16m2_index8
// CHECK-SAME: (ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[INDEX:%.*]], <vscale x 8 x half> [[DATA:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.th.vsxe.nxv8f16.nxv8i8.i64(<vscale x 8 x half> [[DATA]], ptr [[BASE]], <vscale x 8 x i8> [[INDEX]], i64 [[VL]])
// CHECK-NEXT:    ret void
//
void store_f16m2_index8(_Float16 *base, vuint8m1_t index, vfloat16m2_t data, size_t vl) {
  __riscv_th_vsoxei8_v_f16m2(base, index, data, vl);
}

// CHECK-LABEL: define dso_local void @store_f16m2_index8_masked
// CHECK-SAME: (<vscale x 8 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[INDEX:%.*]], <vscale x 8 x half> [[DATA:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.th.vsxe.mask.nxv8f16.nxv8i8.i64(<vscale x 8 x half> [[DATA]], ptr [[BASE]], <vscale x 8 x i8> [[INDEX]], <vscale x 8 x i1> [[MASK]], i64 [[VL]])
// CHECK-NEXT:    ret void
//
void store_f16m2_index8_masked(vbool8_t mask, _Float16 *base, vuint8m1_t index, vfloat16m2_t data, size_t vl) {
  __riscv_th_vsoxei8_v_f16m2_m(mask, base, index, data, vl);
}

// CHECK-LABEL: define dso_local <vscale x 8 x i8> @load_i8m1_index16
// CHECK-SAME: (ptr noundef [[BASE:%.*]], <vscale x 8 x i16> [[INDEX:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.th.vlxe.nxv8i8.nxv8i16.i64(<vscale x 8 x i8> poison, ptr [[BASE]], <vscale x 8 x i16> [[INDEX]], i64 [[VL]])
// CHECK-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vint8m1_t load_i8m1_index16(const int8_t *base, vuint16m2_t index, size_t vl) {
  return __riscv_th_vloxei16_v_i8m1(base, index, vl);
}

// CHECK-LABEL: define dso_local <vscale x 8 x i8> @load_i8m1_index16_masked
// CHECK-SAME: (<vscale x 8 x i1> [[MASK:%.*]], <vscale x 8 x i8> [[MERGE:%.*]], ptr noundef [[BASE:%.*]], <vscale x 8 x i16> [[INDEX:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.th.vlxe.mask.nxv8i8.nxv8i16.i64(<vscale x 8 x i8> [[MERGE]], ptr [[BASE]], <vscale x 8 x i16> [[INDEX]], <vscale x 8 x i1> [[MASK]], i64 [[VL]])
// CHECK-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vint8m1_t load_i8m1_index16_masked(vbool8_t mask, vint8m1_t merge, const int8_t *base, vuint16m2_t index, size_t vl) {
  return __riscv_th_vloxei16_v_i8m1_mu(mask, merge, base, index, vl);
}

// CHECK-LABEL: define dso_local void @store_i8m1_index16
// CHECK-SAME: (ptr noundef [[BASE:%.*]], <vscale x 8 x i16> [[INDEX:%.*]], <vscale x 8 x i8> [[DATA:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.th.vsxe.nxv8i8.nxv8i16.i64(<vscale x 8 x i8> [[DATA]], ptr [[BASE]], <vscale x 8 x i16> [[INDEX]], i64 [[VL]])
// CHECK-NEXT:    ret void
//
void store_i8m1_index16(int8_t *base, vuint16m2_t index, vint8m1_t data, size_t vl) {
  __riscv_th_vsoxei16_v_i8m1(base, index, data, vl);
}

// CHECK-LABEL: define dso_local void @store_i8m1_index16_masked
// CHECK-SAME: (<vscale x 8 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 8 x i16> [[INDEX:%.*]], <vscale x 8 x i8> [[DATA:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.th.vsxe.mask.nxv8i8.nxv8i16.i64(<vscale x 8 x i8> [[DATA]], ptr [[BASE]], <vscale x 8 x i16> [[INDEX]], <vscale x 8 x i1> [[MASK]], i64 [[VL]])
// CHECK-NEXT:    ret void
//
void store_i8m1_index16_masked(vbool8_t mask, int8_t *base, vuint16m2_t index, vint8m1_t data, size_t vl) {
  __riscv_th_vsoxei16_v_i8m1_m(mask, base, index, data, vl);
}

// CHECK-LABEL: define dso_local <vscale x 8 x i64> @load_i64m8_index8
// CHECK-SAME: (ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[INDEX:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i64> @llvm.riscv.th.vlxe.nxv8i64.nxv8i8.i64(<vscale x 8 x i64> poison, ptr [[BASE]], <vscale x 8 x i8> [[INDEX]], i64 [[VL]])
// CHECK-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vint64m8_t load_i64m8_index8(const int64_t *base, vuint8m1_t index, size_t vl) {
  return __riscv_th_vloxei8_v_i64m8(base, index, vl);
}

// CHECK-LABEL: define dso_local <vscale x 8 x i64> @load_i64m8_index8_masked
// CHECK-SAME: (<vscale x 8 x i1> [[MASK:%.*]], <vscale x 8 x i64> [[MERGE:%.*]], ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[INDEX:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i64> @llvm.riscv.th.vlxe.mask.nxv8i64.nxv8i8.i64(<vscale x 8 x i64> [[MERGE]], ptr [[BASE]], <vscale x 8 x i8> [[INDEX]], <vscale x 8 x i1> [[MASK]], i64 [[VL]])
// CHECK-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vint64m8_t load_i64m8_index8_masked(vbool8_t mask, vint64m8_t merge, const int64_t *base, vuint8m1_t index, size_t vl) {
  return __riscv_th_vloxei8_v_i64m8_mu(mask, merge, base, index, vl);
}

// CHECK-LABEL: define dso_local void @store_i64m8_index8
// CHECK-SAME: (ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[INDEX:%.*]], <vscale x 8 x i64> [[DATA:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.th.vsxe.nxv8i64.nxv8i8.i64(<vscale x 8 x i64> [[DATA]], ptr [[BASE]], <vscale x 8 x i8> [[INDEX]], i64 [[VL]])
// CHECK-NEXT:    ret void
//
void store_i64m8_index8(int64_t *base, vuint8m1_t index, vint64m8_t data, size_t vl) {
  __riscv_th_vsoxei8_v_i64m8(base, index, data, vl);
}

// CHECK-LABEL: define dso_local void @store_i64m8_index8_masked
// CHECK-SAME: (<vscale x 8 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[INDEX:%.*]], <vscale x 8 x i64> [[DATA:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.th.vsxe.mask.nxv8i64.nxv8i8.i64(<vscale x 8 x i64> [[DATA]], ptr [[BASE]], <vscale x 8 x i8> [[INDEX]], <vscale x 8 x i1> [[MASK]], i64 [[VL]])
// CHECK-NEXT:    ret void
//
void store_i64m8_index8_masked(vbool8_t mask, int64_t *base, vuint8m1_t index, vint64m8_t data, size_t vl) {
  __riscv_th_vsoxei8_v_i64m8_m(mask, base, index, data, vl);
}

// CHECK-LABEL: define dso_local <vscale x 8 x float> @load_f32m4_index64
// CHECK-SAME: (ptr noundef [[BASE:%.*]], <vscale x 8 x i64> [[INDEX:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x float> @llvm.riscv.th.vlxe.nxv8f32.nxv8i64.i64(<vscale x 8 x float> poison, ptr [[BASE]], <vscale x 8 x i64> [[INDEX]], i64 [[VL]])
// CHECK-NEXT:    ret <vscale x 8 x float> [[TMP0]]
//
vfloat32m4_t load_f32m4_index64(const float *base, vuint64m8_t index, size_t vl) {
  return __riscv_th_vloxei64_v_f32m4(base, index, vl);
}

// CHECK-LABEL: define dso_local <vscale x 8 x float> @load_f32m4_index64_masked
// CHECK-SAME: (<vscale x 8 x i1> [[MASK:%.*]], <vscale x 8 x float> [[MERGE:%.*]], ptr noundef [[BASE:%.*]], <vscale x 8 x i64> [[INDEX:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x float> @llvm.riscv.th.vlxe.mask.nxv8f32.nxv8i64.i64(<vscale x 8 x float> [[MERGE]], ptr [[BASE]], <vscale x 8 x i64> [[INDEX]], <vscale x 8 x i1> [[MASK]], i64 [[VL]])
// CHECK-NEXT:    ret <vscale x 8 x float> [[TMP0]]
//
vfloat32m4_t load_f32m4_index64_masked(vbool8_t mask, vfloat32m4_t merge, const float *base, vuint64m8_t index, size_t vl) {
  return __riscv_th_vloxei64_v_f32m4_mu(mask, merge, base, index, vl);
}

// CHECK-LABEL: define dso_local void @store_f32m4_index64
// CHECK-SAME: (ptr noundef [[BASE:%.*]], <vscale x 8 x i64> [[INDEX:%.*]], <vscale x 8 x float> [[DATA:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.th.vsxe.nxv8f32.nxv8i64.i64(<vscale x 8 x float> [[DATA]], ptr [[BASE]], <vscale x 8 x i64> [[INDEX]], i64 [[VL]])
// CHECK-NEXT:    ret void
//
void store_f32m4_index64(float *base, vuint64m8_t index, vfloat32m4_t data, size_t vl) {
  __riscv_th_vsoxei64_v_f32m4(base, index, data, vl);
}

// CHECK-LABEL: define dso_local void @store_f32m4_index64_masked
// CHECK-SAME: (<vscale x 8 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 8 x i64> [[INDEX:%.*]], <vscale x 8 x float> [[DATA:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.th.vsxe.mask.nxv8f32.nxv8i64.i64(<vscale x 8 x float> [[DATA]], ptr [[BASE]], <vscale x 8 x i64> [[INDEX]], <vscale x 8 x i1> [[MASK]], i64 [[VL]])
// CHECK-NEXT:    ret void
//
void store_f32m4_index64_masked(vbool8_t mask, float *base, vuint64m8_t index, vfloat32m4_t data, size_t vl) {
  __riscv_th_vsoxei64_v_f32m4_m(mask, base, index, data, vl);
}

// CHECK-LABEL: define dso_local <vscale x 8 x i16> @load_i16m2_index8_mask_agnostic
// CHECK-SAME: (<vscale x 8 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[INDEX:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.th.vlxe.mask.nxv8i16.nxv8i8.i64(<vscale x 8 x i16> poison, ptr [[BASE]], <vscale x 8 x i8> [[INDEX]], <vscale x 8 x i1> [[MASK]], i64 [[VL]])
// CHECK-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vint16m2_t load_i16m2_index8_mask_agnostic(vbool8_t mask, const int16_t *base,
                                         vuint8m1_t index, size_t vl) {
  return __riscv_th_vloxei8_v_i16m2_m(mask, base, index, vl);
}
