; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: sed 's/iXLen/i32/g' %s | llc -mtriple=riscv32 -mattr=+xtheadvector -verify-machineinstrs | FileCheck %s
; RUN: sed 's/iXLen/i64/g' %s | llc -mtriple=riscv64 -mattr=+xtheadvector -verify-machineinstrs | FileCheck %s

; Indices are signed byte offsets (RVV 0.7.1). Exercise both directions of
; width conversion, preserving memory element size and masked-off data.

define <vscale x 8 x i16> @load_i16_index8(ptr %base, <vscale x 8 x i8> %index, iXLen %vl) {
; CHECK-LABEL: load_i16_index8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; CHECK-NEXT:    th.vwcvt.x.x.v v10, v8
; CHECK-NEXT:    th.vsetvli zero, zero, e16, m2, d1
; CHECK-NEXT:    th.vlxe.v v8, (a0), v10
; CHECK-NEXT:    ret
  %result = call <vscale x 8 x i16> @llvm.riscv.th.vlxe.nxv8i16.nxv8i8(<vscale x 8 x i16> poison, ptr %base, <vscale x 8 x i8> %index, iXLen %vl)
  ret <vscale x 8 x i16> %result
}

declare <vscale x 8 x i16> @llvm.riscv.th.vlxe.nxv8i16.nxv8i8(<vscale x 8 x i16>, ptr, <vscale x 8 x i8>, iXLen)

define <vscale x 8 x i16> @load_i16_index8_masked(ptr %base, <vscale x 8 x i8> %index, <vscale x 8 x i16> %data, <vscale x 8 x i1> %mask, iXLen %vl) {
; CHECK-LABEL: load_i16_index8_masked:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; CHECK-NEXT:    th.vwcvt.x.x.v v12, v8
; CHECK-NEXT:    th.vsetvli zero, zero, e16, m2, d1
; CHECK-NEXT:    th.vlxe.v v10, (a0), v12, v0.t
; CHECK-NEXT:    th.vmv.v.v v8, v10
; CHECK-NEXT:    ret
  %result = call <vscale x 8 x i16> @llvm.riscv.th.vlxe.mask.nxv8i16.nxv8i8(<vscale x 8 x i16> %data, ptr %base, <vscale x 8 x i8> %index, <vscale x 8 x i1> %mask, iXLen %vl)
  ret <vscale x 8 x i16> %result
}

declare <vscale x 8 x i16> @llvm.riscv.th.vlxe.mask.nxv8i16.nxv8i8(<vscale x 8 x i16>, ptr, <vscale x 8 x i8>, <vscale x 8 x i1>, iXLen)

define void @store_i16_index8(ptr %base, <vscale x 8 x i8> %index, <vscale x 8 x i16> %data, iXLen %vl) {
; CHECK-LABEL: store_i16_index8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; CHECK-NEXT:    th.vwcvt.x.x.v v12, v8
; CHECK-NEXT:    th.vsetvli zero, zero, e16, m2, d1
; CHECK-NEXT:    th.vsxe.v v10, (a0), v12
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.vsxe.nxv8i16.nxv8i8(<vscale x 8 x i16> %data, ptr %base, <vscale x 8 x i8> %index, iXLen %vl)
  ret void
}

declare void @llvm.riscv.th.vsxe.nxv8i16.nxv8i8(<vscale x 8 x i16>, ptr, <vscale x 8 x i8>, iXLen)

define void @store_i16_index8_masked(ptr %base, <vscale x 8 x i8> %index, <vscale x 8 x i16> %data, <vscale x 8 x i1> %mask, iXLen %vl) {
; CHECK-LABEL: store_i16_index8_masked:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; CHECK-NEXT:    th.vwcvt.x.x.v v12, v8
; CHECK-NEXT:    th.vsetvli zero, zero, e16, m2, d1
; CHECK-NEXT:    th.vsxe.v v10, (a0), v12, v0.t
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.vsxe.mask.nxv8i16.nxv8i8(<vscale x 8 x i16> %data, ptr %base, <vscale x 8 x i8> %index, <vscale x 8 x i1> %mask, iXLen %vl)
  ret void
}

declare void @llvm.riscv.th.vsxe.mask.nxv8i16.nxv8i8(<vscale x 8 x i16>, ptr, <vscale x 8 x i8>, <vscale x 8 x i1>, iXLen)

define <vscale x 8 x i8> @load_i8_index16(ptr %base, <vscale x 8 x i16> %index, iXLen %vl) {
; CHECK-LABEL: load_i8_index16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.vsetvli zero, a1, e16, m2, d1
; CHECK-NEXT:    th.vlxbu.v v10, (a0), v8
; CHECK-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; CHECK-NEXT:    th.vnsrl.vx v8, v10, zero
; CHECK-NEXT:    ret
  %result = call <vscale x 8 x i8> @llvm.riscv.th.vlxe.nxv8i8.nxv8i16(<vscale x 8 x i8> poison, ptr %base, <vscale x 8 x i16> %index, iXLen %vl)
  ret <vscale x 8 x i8> %result
}

declare <vscale x 8 x i8> @llvm.riscv.th.vlxe.nxv8i8.nxv8i16(<vscale x 8 x i8>, ptr, <vscale x 8 x i16>, iXLen)

define <vscale x 8 x i8> @load_i8_index16_masked(ptr %base, <vscale x 8 x i16> %index, <vscale x 8 x i8> %data, <vscale x 8 x i1> %mask, iXLen %vl) {
; CHECK-LABEL: load_i8_index16_masked:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; CHECK-NEXT:    th.vwcvtu.x.x.v v12, v10
; CHECK-NEXT:    th.vsetvli zero, zero, e16, m2, d1
; CHECK-NEXT:    th.vlxbu.v v12, (a0), v8, v0.t
; CHECK-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; CHECK-NEXT:    th.vnsrl.vx v10, v12, zero
; CHECK-NEXT:    th.vmv.v.v v8, v10
; CHECK-NEXT:    ret
  %result = call <vscale x 8 x i8> @llvm.riscv.th.vlxe.mask.nxv8i8.nxv8i16(<vscale x 8 x i8> %data, ptr %base, <vscale x 8 x i16> %index, <vscale x 8 x i1> %mask, iXLen %vl)
  ret <vscale x 8 x i8> %result
}

declare <vscale x 8 x i8> @llvm.riscv.th.vlxe.mask.nxv8i8.nxv8i16(<vscale x 8 x i8>, ptr, <vscale x 8 x i16>, <vscale x 8 x i1>, iXLen)

define void @store_i8_index16(ptr %base, <vscale x 8 x i16> %index, <vscale x 8 x i8> %data, iXLen %vl) {
; CHECK-LABEL: store_i8_index16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; CHECK-NEXT:    th.vwcvtu.x.x.v v12, v10
; CHECK-NEXT:    th.vsetvli zero, zero, e16, m2, d1
; CHECK-NEXT:    th.vsxb.v v12, (a0), v8
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.vsxe.nxv8i8.nxv8i16(<vscale x 8 x i8> %data, ptr %base, <vscale x 8 x i16> %index, iXLen %vl)
  ret void
}

declare void @llvm.riscv.th.vsxe.nxv8i8.nxv8i16(<vscale x 8 x i8>, ptr, <vscale x 8 x i16>, iXLen)

define void @store_i8_index16_masked(ptr %base, <vscale x 8 x i16> %index, <vscale x 8 x i8> %data, <vscale x 8 x i1> %mask, iXLen %vl) {
; CHECK-LABEL: store_i8_index16_masked:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; CHECK-NEXT:    th.vwcvtu.x.x.v v12, v10
; CHECK-NEXT:    th.vsetvli zero, zero, e16, m2, d1
; CHECK-NEXT:    th.vsxb.v v12, (a0), v8, v0.t
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.vsxe.mask.nxv8i8.nxv8i16(<vscale x 8 x i8> %data, ptr %base, <vscale x 8 x i16> %index, <vscale x 8 x i1> %mask, iXLen %vl)
  ret void
}

declare void @llvm.riscv.th.vsxe.mask.nxv8i8.nxv8i16(<vscale x 8 x i8>, ptr, <vscale x 8 x i16>, <vscale x 8 x i1>, iXLen)

define <vscale x 8 x i32> @load_i32_index8(ptr %base, <vscale x 8 x i8> %index, iXLen %vl) {
; CHECK-LABEL: load_i32_index8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; CHECK-NEXT:    th.vwcvt.x.x.v v10, v8
; CHECK-NEXT:    th.vsetvli zero, zero, e16, m2, d1
; CHECK-NEXT:    th.vwcvt.x.x.v v12, v10
; CHECK-NEXT:    th.vsetvli zero, zero, e32, m4, d1
; CHECK-NEXT:    th.vlxe.v v8, (a0), v12
; CHECK-NEXT:    ret
  %result = call <vscale x 8 x i32> @llvm.riscv.th.vlxe.nxv8i32.nxv8i8(<vscale x 8 x i32> poison, ptr %base, <vscale x 8 x i8> %index, iXLen %vl)
  ret <vscale x 8 x i32> %result
}

declare <vscale x 8 x i32> @llvm.riscv.th.vlxe.nxv8i32.nxv8i8(<vscale x 8 x i32>, ptr, <vscale x 8 x i8>, iXLen)

define <vscale x 8 x i32> @load_i32_index8_masked(ptr %base, <vscale x 8 x i8> %index, <vscale x 8 x i32> %data, <vscale x 8 x i1> %mask, iXLen %vl) {
; CHECK-LABEL: load_i32_index8_masked:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; CHECK-NEXT:    th.vwcvt.x.x.v v10, v8
; CHECK-NEXT:    th.vsetvli zero, zero, e16, m2, d1
; CHECK-NEXT:    th.vwcvt.x.x.v v16, v10
; CHECK-NEXT:    th.vsetvli zero, zero, e32, m4, d1
; CHECK-NEXT:    th.vlxe.v v12, (a0), v16, v0.t
; CHECK-NEXT:    th.vmv.v.v v8, v12
; CHECK-NEXT:    ret
  %result = call <vscale x 8 x i32> @llvm.riscv.th.vlxe.mask.nxv8i32.nxv8i8(<vscale x 8 x i32> %data, ptr %base, <vscale x 8 x i8> %index, <vscale x 8 x i1> %mask, iXLen %vl)
  ret <vscale x 8 x i32> %result
}

declare <vscale x 8 x i32> @llvm.riscv.th.vlxe.mask.nxv8i32.nxv8i8(<vscale x 8 x i32>, ptr, <vscale x 8 x i8>, <vscale x 8 x i1>, iXLen)

define void @store_i32_index8(ptr %base, <vscale x 8 x i8> %index, <vscale x 8 x i32> %data, iXLen %vl) {
; CHECK-LABEL: store_i32_index8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; CHECK-NEXT:    th.vwcvt.x.x.v v10, v8
; CHECK-NEXT:    th.vsetvli zero, zero, e16, m2, d1
; CHECK-NEXT:    th.vwcvt.x.x.v v16, v10
; CHECK-NEXT:    th.vsetvli zero, zero, e32, m4, d1
; CHECK-NEXT:    th.vsxe.v v12, (a0), v16
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.vsxe.nxv8i32.nxv8i8(<vscale x 8 x i32> %data, ptr %base, <vscale x 8 x i8> %index, iXLen %vl)
  ret void
}

declare void @llvm.riscv.th.vsxe.nxv8i32.nxv8i8(<vscale x 8 x i32>, ptr, <vscale x 8 x i8>, iXLen)

define void @store_i32_index8_masked(ptr %base, <vscale x 8 x i8> %index, <vscale x 8 x i32> %data, <vscale x 8 x i1> %mask, iXLen %vl) {
; CHECK-LABEL: store_i32_index8_masked:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; CHECK-NEXT:    th.vwcvt.x.x.v v10, v8
; CHECK-NEXT:    th.vsetvli zero, zero, e16, m2, d1
; CHECK-NEXT:    th.vwcvt.x.x.v v16, v10
; CHECK-NEXT:    th.vsetvli zero, zero, e32, m4, d1
; CHECK-NEXT:    th.vsxe.v v12, (a0), v16, v0.t
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.vsxe.mask.nxv8i32.nxv8i8(<vscale x 8 x i32> %data, ptr %base, <vscale x 8 x i8> %index, <vscale x 8 x i1> %mask, iXLen %vl)
  ret void
}

declare void @llvm.riscv.th.vsxe.mask.nxv8i32.nxv8i8(<vscale x 8 x i32>, ptr, <vscale x 8 x i8>, <vscale x 8 x i1>, iXLen)

define <vscale x 8 x i8> @load_i8_index32(ptr %base, <vscale x 8 x i32> %index, iXLen %vl) {
; CHECK-LABEL: load_i8_index32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.vsetvli zero, a1, e32, m4, d1
; CHECK-NEXT:    th.vlxbu.v v8, (a0), v8
; CHECK-NEXT:    th.vsetvli zero, zero, e16, m2, d1
; CHECK-NEXT:    th.vnsrl.vx v12, v8, zero
; CHECK-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; CHECK-NEXT:    th.vnsrl.vx v8, v12, zero
; CHECK-NEXT:    ret
  %result = call <vscale x 8 x i8> @llvm.riscv.th.vlxe.nxv8i8.nxv8i32(<vscale x 8 x i8> poison, ptr %base, <vscale x 8 x i32> %index, iXLen %vl)
  ret <vscale x 8 x i8> %result
}

declare <vscale x 8 x i8> @llvm.riscv.th.vlxe.nxv8i8.nxv8i32(<vscale x 8 x i8>, ptr, <vscale x 8 x i32>, iXLen)

define <vscale x 8 x i8> @load_i8_index32_masked(ptr %base, <vscale x 8 x i32> %index, <vscale x 8 x i8> %data, <vscale x 8 x i1> %mask, iXLen %vl) {
; CHECK-LABEL: load_i8_index32_masked:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; CHECK-NEXT:    th.vwcvtu.x.x.v v14, v12
; CHECK-NEXT:    th.vsetvli zero, zero, e16, m2, d1
; CHECK-NEXT:    th.vwcvtu.x.x.v v16, v14
; CHECK-NEXT:    th.vsetvli zero, zero, e32, m4, d1
; CHECK-NEXT:    th.vlxbu.v v16, (a0), v8, v0.t
; CHECK-NEXT:    th.vsetvli zero, zero, e16, m2, d1
; CHECK-NEXT:    th.vnsrl.vx v8, v16, zero
; CHECK-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; CHECK-NEXT:    th.vnsrl.vx v12, v8, zero
; CHECK-NEXT:    th.vmv.v.v v8, v12
; CHECK-NEXT:    ret
  %result = call <vscale x 8 x i8> @llvm.riscv.th.vlxe.mask.nxv8i8.nxv8i32(<vscale x 8 x i8> %data, ptr %base, <vscale x 8 x i32> %index, <vscale x 8 x i1> %mask, iXLen %vl)
  ret <vscale x 8 x i8> %result
}

declare <vscale x 8 x i8> @llvm.riscv.th.vlxe.mask.nxv8i8.nxv8i32(<vscale x 8 x i8>, ptr, <vscale x 8 x i32>, <vscale x 8 x i1>, iXLen)

define void @store_i8_index32(ptr %base, <vscale x 8 x i32> %index, <vscale x 8 x i8> %data, iXLen %vl) {
; CHECK-LABEL: store_i8_index32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; CHECK-NEXT:    th.vwcvtu.x.x.v v14, v12
; CHECK-NEXT:    th.vsetvli zero, zero, e16, m2, d1
; CHECK-NEXT:    th.vwcvtu.x.x.v v16, v14
; CHECK-NEXT:    th.vsetvli zero, zero, e32, m4, d1
; CHECK-NEXT:    th.vsxb.v v16, (a0), v8
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.vsxe.nxv8i8.nxv8i32(<vscale x 8 x i8> %data, ptr %base, <vscale x 8 x i32> %index, iXLen %vl)
  ret void
}

declare void @llvm.riscv.th.vsxe.nxv8i8.nxv8i32(<vscale x 8 x i8>, ptr, <vscale x 8 x i32>, iXLen)

define void @store_i8_index32_masked(ptr %base, <vscale x 8 x i32> %index, <vscale x 8 x i8> %data, <vscale x 8 x i1> %mask, iXLen %vl) {
; CHECK-LABEL: store_i8_index32_masked:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; CHECK-NEXT:    th.vwcvtu.x.x.v v14, v12
; CHECK-NEXT:    th.vsetvli zero, zero, e16, m2, d1
; CHECK-NEXT:    th.vwcvtu.x.x.v v16, v14
; CHECK-NEXT:    th.vsetvli zero, zero, e32, m4, d1
; CHECK-NEXT:    th.vsxb.v v16, (a0), v8, v0.t
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.vsxe.mask.nxv8i8.nxv8i32(<vscale x 8 x i8> %data, ptr %base, <vscale x 8 x i32> %index, <vscale x 8 x i1> %mask, iXLen %vl)
  ret void
}

declare void @llvm.riscv.th.vsxe.mask.nxv8i8.nxv8i32(<vscale x 8 x i8>, ptr, <vscale x 8 x i32>, <vscale x 8 x i1>, iXLen)

define <vscale x 8 x half> @load_f16_index8(ptr %base, <vscale x 8 x i8> %index, iXLen %vl) {
; CHECK-LABEL: load_f16_index8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; CHECK-NEXT:    th.vwcvt.x.x.v v10, v8
; CHECK-NEXT:    th.vsetvli zero, zero, e16, m2, d1
; CHECK-NEXT:    th.vlxe.v v8, (a0), v10
; CHECK-NEXT:    ret
  %result = call <vscale x 8 x half> @llvm.riscv.th.vlxe.nxv8f16.nxv8i8(<vscale x 8 x half> poison, ptr %base, <vscale x 8 x i8> %index, iXLen %vl)
  ret <vscale x 8 x half> %result
}

declare <vscale x 8 x half> @llvm.riscv.th.vlxe.nxv8f16.nxv8i8(<vscale x 8 x half>, ptr, <vscale x 8 x i8>, iXLen)

define <vscale x 8 x half> @load_f16_index8_masked(ptr %base, <vscale x 8 x i8> %index, <vscale x 8 x half> %data, <vscale x 8 x i1> %mask, iXLen %vl) {
; CHECK-LABEL: load_f16_index8_masked:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; CHECK-NEXT:    th.vwcvt.x.x.v v12, v8
; CHECK-NEXT:    th.vsetvli zero, zero, e16, m2, d1
; CHECK-NEXT:    th.vlxe.v v10, (a0), v12, v0.t
; CHECK-NEXT:    th.vmv.v.v v8, v10
; CHECK-NEXT:    ret
  %result = call <vscale x 8 x half> @llvm.riscv.th.vlxe.mask.nxv8f16.nxv8i8(<vscale x 8 x half> %data, ptr %base, <vscale x 8 x i8> %index, <vscale x 8 x i1> %mask, iXLen %vl)
  ret <vscale x 8 x half> %result
}

declare <vscale x 8 x half> @llvm.riscv.th.vlxe.mask.nxv8f16.nxv8i8(<vscale x 8 x half>, ptr, <vscale x 8 x i8>, <vscale x 8 x i1>, iXLen)

define void @store_f16_index8(ptr %base, <vscale x 8 x i8> %index, <vscale x 8 x half> %data, iXLen %vl) {
; CHECK-LABEL: store_f16_index8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; CHECK-NEXT:    th.vwcvt.x.x.v v12, v8
; CHECK-NEXT:    th.vsetvli zero, zero, e16, m2, d1
; CHECK-NEXT:    th.vsxe.v v10, (a0), v12
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.vsxe.nxv8f16.nxv8i8(<vscale x 8 x half> %data, ptr %base, <vscale x 8 x i8> %index, iXLen %vl)
  ret void
}

declare void @llvm.riscv.th.vsxe.nxv8f16.nxv8i8(<vscale x 8 x half>, ptr, <vscale x 8 x i8>, iXLen)

define void @store_f16_index8_masked(ptr %base, <vscale x 8 x i8> %index, <vscale x 8 x half> %data, <vscale x 8 x i1> %mask, iXLen %vl) {
; CHECK-LABEL: store_f16_index8_masked:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; CHECK-NEXT:    th.vwcvt.x.x.v v12, v8
; CHECK-NEXT:    th.vsetvli zero, zero, e16, m2, d1
; CHECK-NEXT:    th.vsxe.v v10, (a0), v12, v0.t
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.vsxe.mask.nxv8f16.nxv8i8(<vscale x 8 x half> %data, ptr %base, <vscale x 8 x i8> %index, <vscale x 8 x i1> %mask, iXLen %vl)
  ret void
}

declare void @llvm.riscv.th.vsxe.mask.nxv8f16.nxv8i8(<vscale x 8 x half>, ptr, <vscale x 8 x i8>, <vscale x 8 x i1>, iXLen)

define <vscale x 8 x half> @load_f16_index32(ptr %base, <vscale x 8 x i32> %index, iXLen %vl) {
; CHECK-LABEL: load_f16_index32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.vsetvli zero, a1, e32, m4, d1
; CHECK-NEXT:    th.vlxhu.v v12, (a0), v8
; CHECK-NEXT:    th.vsetvli zero, zero, e16, m2, d1
; CHECK-NEXT:    th.vnsrl.vx v8, v12, zero
; CHECK-NEXT:    ret
  %result = call <vscale x 8 x half> @llvm.riscv.th.vlxe.nxv8f16.nxv8i32(<vscale x 8 x half> poison, ptr %base, <vscale x 8 x i32> %index, iXLen %vl)
  ret <vscale x 8 x half> %result
}

declare <vscale x 8 x half> @llvm.riscv.th.vlxe.nxv8f16.nxv8i32(<vscale x 8 x half>, ptr, <vscale x 8 x i32>, iXLen)

define <vscale x 8 x half> @load_f16_index32_masked(ptr %base, <vscale x 8 x i32> %index, <vscale x 8 x half> %data, <vscale x 8 x i1> %mask, iXLen %vl) {
; CHECK-LABEL: load_f16_index32_masked:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.vsetvli zero, a1, e16, m2, d1
; CHECK-NEXT:    th.vwcvtu.x.x.v v16, v12
; CHECK-NEXT:    th.vsetvli zero, zero, e32, m4, d1
; CHECK-NEXT:    th.vlxhu.v v16, (a0), v8, v0.t
; CHECK-NEXT:    th.vsetvli zero, zero, e16, m2, d1
; CHECK-NEXT:    th.vnsrl.vx v12, v16, zero
; CHECK-NEXT:    th.vmv.v.v v8, v12
; CHECK-NEXT:    ret
  %result = call <vscale x 8 x half> @llvm.riscv.th.vlxe.mask.nxv8f16.nxv8i32(<vscale x 8 x half> %data, ptr %base, <vscale x 8 x i32> %index, <vscale x 8 x i1> %mask, iXLen %vl)
  ret <vscale x 8 x half> %result
}

declare <vscale x 8 x half> @llvm.riscv.th.vlxe.mask.nxv8f16.nxv8i32(<vscale x 8 x half>, ptr, <vscale x 8 x i32>, <vscale x 8 x i1>, iXLen)

define void @store_f16_index32(ptr %base, <vscale x 8 x i32> %index, <vscale x 8 x half> %data, iXLen %vl) {
; CHECK-LABEL: store_f16_index32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.vsetvli zero, a1, e16, m2, d1
; CHECK-NEXT:    th.vwcvtu.x.x.v v16, v12
; CHECK-NEXT:    th.vsetvli zero, zero, e32, m4, d1
; CHECK-NEXT:    th.vsxh.v v16, (a0), v8
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.vsxe.nxv8f16.nxv8i32(<vscale x 8 x half> %data, ptr %base, <vscale x 8 x i32> %index, iXLen %vl)
  ret void
}

declare void @llvm.riscv.th.vsxe.nxv8f16.nxv8i32(<vscale x 8 x half>, ptr, <vscale x 8 x i32>, iXLen)

define void @store_f16_index32_masked(ptr %base, <vscale x 8 x i32> %index, <vscale x 8 x half> %data, <vscale x 8 x i1> %mask, iXLen %vl) {
; CHECK-LABEL: store_f16_index32_masked:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.vsetvli zero, a1, e16, m2, d1
; CHECK-NEXT:    th.vwcvtu.x.x.v v16, v12
; CHECK-NEXT:    th.vsetvli zero, zero, e32, m4, d1
; CHECK-NEXT:    th.vsxh.v v16, (a0), v8, v0.t
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.vsxe.mask.nxv8f16.nxv8i32(<vscale x 8 x half> %data, ptr %base, <vscale x 8 x i32> %index, <vscale x 8 x i1> %mask, iXLen %vl)
  ret void
}

declare void @llvm.riscv.th.vsxe.mask.nxv8f16.nxv8i32(<vscale x 8 x half>, ptr, <vscale x 8 x i32>, <vscale x 8 x i1>, iXLen)

; No elements are updated when vl=0, including the original passthru.
define <vscale x 8 x i8> @load_i8_index16_vl0(<vscale x 8 x i8> %passthru, ptr %base, <vscale x 8 x i16> %index) {
; CHECK-LABEL: load_i8_index16_vl0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ret
  %result = call <vscale x 8 x i8> @llvm.riscv.th.vlxe.nxv8i8.nxv8i16(<vscale x 8 x i8> %passthru, ptr %base, <vscale x 8 x i16> %index, iXLen 0)
  ret <vscale x 8 x i8> %result
}

define void @store_i8_index16_vl0(ptr %base, <vscale x 8 x i16> %index, <vscale x 8 x i8> %data) {
; CHECK-LABEL: store_i8_index16_vl0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.vsxe.nxv8i8.nxv8i16(<vscale x 8 x i8> %data, ptr %base, <vscale x 8 x i16> %index, iXLen 0)
  ret void
}

; Sign extension must preserve negative offsets, not interpret 0x80 as +128.
define <vscale x 8 x i16> @load_i16_negative_index8(ptr %base, iXLen %vl) {
; CHECK-LABEL: load_i16_negative_index8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a2, -128
; CHECK-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; CHECK-NEXT:    th.vmv.v.x v8, a2
; CHECK-NEXT:    th.vwcvt.x.x.v v10, v8
; CHECK-NEXT:    th.vsetvli zero, zero, e16, m2, d1
; CHECK-NEXT:    th.vlxe.v v8, (a0), v10
; CHECK-NEXT:    ret
  %index = call <vscale x 8 x i8> @llvm.riscv.th.vmv.v.x.nxv8i8(<vscale x 8 x i8> poison, i8 -128, iXLen %vl)
  %result = call <vscale x 8 x i16> @llvm.riscv.th.vlxe.nxv8i16.nxv8i8(<vscale x 8 x i16> poison, ptr %base, <vscale x 8 x i8> %index, iXLen %vl)
  ret <vscale x 8 x i16> %result
}

declare <vscale x 8 x i8> @llvm.riscv.th.vmv.v.x.nxv8i8(<vscale x 8 x i8>, i8, iXLen)

; Widen the byte data instead of truncating the index to zero.
define void @store_i8_large_index32(ptr %base, <vscale x 8 x i8> %data, iXLen %vl) {
; CHECK-LABEL: store_i8_large_index32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a2, 16
; CHECK-NEXT:    th.vsetvli zero, a1, e32, m4, d1
; CHECK-NEXT:    th.vmv.v.x v12, a2
; CHECK-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; CHECK-NEXT:    th.vwcvtu.x.x.v v10, v8
; CHECK-NEXT:    th.vsetvli zero, zero, e16, m2, d1
; CHECK-NEXT:    th.vwcvtu.x.x.v v16, v10
; CHECK-NEXT:    th.vsetvli zero, zero, e32, m4, d1
; CHECK-NEXT:    th.vsxb.v v16, (a0), v12
; CHECK-NEXT:    ret
  %index = call <vscale x 8 x i32> @llvm.riscv.th.vmv.v.x.nxv8i32(<vscale x 8 x i32> poison, i32 65536, iXLen %vl)
  call void @llvm.riscv.th.vsxe.nxv8i8.nxv8i32(<vscale x 8 x i8> %data, ptr %base, <vscale x 8 x i32> %index, iXLen %vl)
  ret void
}

declare <vscale x 8 x i32> @llvm.riscv.th.vmv.v.x.nxv8i32(<vscale x 8 x i32>, i32, iXLen)
