; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -mtriple=riscv64 -mattr=+xtheadvector -verify-machineinstrs < %s | FileCheck %s

; Indices are signed byte offsets (RVV 0.7.1). Exercise both directions of
; width conversion, preserving memory element size and masked-off data.

define <vscale x 8 x i64> @load_i64_index8(ptr %base, <vscale x 8 x i8> %index, i64 %vl) {
; CHECK-LABEL: load_i64_index8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; CHECK-NEXT:    th.vwcvt.x.x.v v10, v8
; CHECK-NEXT:    th.vsetvli zero, zero, e16, m2, d1
; CHECK-NEXT:    th.vwcvt.x.x.v v12, v10
; CHECK-NEXT:    th.vsetvli zero, zero, e32, m4, d1
; CHECK-NEXT:    th.vwcvt.x.x.v v16, v12
; CHECK-NEXT:    th.vsetvli zero, zero, e64, m8, d1
; CHECK-NEXT:    th.vlxe.v v8, (a0), v16
; CHECK-NEXT:    ret
  %result = call <vscale x 8 x i64> @llvm.riscv.th.vlxe.nxv8i64.nxv8i8(<vscale x 8 x i64> poison, ptr %base, <vscale x 8 x i8> %index, i64 %vl)
  ret <vscale x 8 x i64> %result
}

declare <vscale x 8 x i64> @llvm.riscv.th.vlxe.nxv8i64.nxv8i8(<vscale x 8 x i64>, ptr, <vscale x 8 x i8>, i64)

define <vscale x 8 x i64> @load_i64_index8_masked(ptr %base, <vscale x 8 x i8> %index, <vscale x 8 x i64> %data, <vscale x 8 x i1> %mask, i64 %vl) {
; CHECK-LABEL: load_i64_index8_masked:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; CHECK-NEXT:    th.vwcvt.x.x.v v10, v8
; CHECK-NEXT:    th.vsetvli zero, zero, e16, m2, d1
; CHECK-NEXT:    th.vwcvt.x.x.v v24, v10
; CHECK-NEXT:    th.vsetvli zero, zero, e32, m4, d1
; CHECK-NEXT:    th.vwcvt.x.x.v v8, v24
; CHECK-NEXT:    th.vsetvli zero, zero, e64, m8, d1
; CHECK-NEXT:    th.vlxe.v v16, (a0), v8, v0.t
; CHECK-NEXT:    th.vmv.v.v v8, v16
; CHECK-NEXT:    ret
  %result = call <vscale x 8 x i64> @llvm.riscv.th.vlxe.mask.nxv8i64.nxv8i8(<vscale x 8 x i64> %data, ptr %base, <vscale x 8 x i8> %index, <vscale x 8 x i1> %mask, i64 %vl)
  ret <vscale x 8 x i64> %result
}

declare <vscale x 8 x i64> @llvm.riscv.th.vlxe.mask.nxv8i64.nxv8i8(<vscale x 8 x i64>, ptr, <vscale x 8 x i8>, <vscale x 8 x i1>, i64)

define void @store_i64_index8(ptr %base, <vscale x 8 x i8> %index, <vscale x 8 x i64> %data, i64 %vl) {
; CHECK-LABEL: store_i64_index8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; CHECK-NEXT:    th.vwcvt.x.x.v v10, v8
; CHECK-NEXT:    th.vsetvli zero, zero, e16, m2, d1
; CHECK-NEXT:    th.vwcvt.x.x.v v12, v10
; CHECK-NEXT:    th.vsetvli zero, zero, e32, m4, d1
; CHECK-NEXT:    th.vwcvt.x.x.v v24, v12
; CHECK-NEXT:    th.vsetvli zero, zero, e64, m8, d1
; CHECK-NEXT:    th.vsxe.v v16, (a0), v24
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.vsxe.nxv8i64.nxv8i8(<vscale x 8 x i64> %data, ptr %base, <vscale x 8 x i8> %index, i64 %vl)
  ret void
}

declare void @llvm.riscv.th.vsxe.nxv8i64.nxv8i8(<vscale x 8 x i64>, ptr, <vscale x 8 x i8>, i64)

define void @store_i64_index8_masked(ptr %base, <vscale x 8 x i8> %index, <vscale x 8 x i64> %data, <vscale x 8 x i1> %mask, i64 %vl) {
; CHECK-LABEL: store_i64_index8_masked:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; CHECK-NEXT:    th.vwcvt.x.x.v v10, v8
; CHECK-NEXT:    th.vsetvli zero, zero, e16, m2, d1
; CHECK-NEXT:    th.vwcvt.x.x.v v12, v10
; CHECK-NEXT:    th.vsetvli zero, zero, e32, m4, d1
; CHECK-NEXT:    th.vwcvt.x.x.v v24, v12
; CHECK-NEXT:    th.vsetvli zero, zero, e64, m8, d1
; CHECK-NEXT:    th.vsxe.v v16, (a0), v24, v0.t
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.vsxe.mask.nxv8i64.nxv8i8(<vscale x 8 x i64> %data, ptr %base, <vscale x 8 x i8> %index, <vscale x 8 x i1> %mask, i64 %vl)
  ret void
}

declare void @llvm.riscv.th.vsxe.mask.nxv8i64.nxv8i8(<vscale x 8 x i64>, ptr, <vscale x 8 x i8>, <vscale x 8 x i1>, i64)

define <vscale x 8 x i8> @load_i8_index64(ptr %base, <vscale x 8 x i64> %index, i64 %vl) {
; CHECK-LABEL: load_i8_index64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.vsetvli zero, a1, e64, m8, d1
; CHECK-NEXT:    th.vlxbu.v v8, (a0), v8
; CHECK-NEXT:    th.vsetvli zero, zero, e32, m4, d1
; CHECK-NEXT:    th.vnsrl.vx v16, v8, zero
; CHECK-NEXT:    th.vsetvli zero, zero, e16, m2, d1
; CHECK-NEXT:    th.vnsrl.vx v10, v16, zero
; CHECK-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; CHECK-NEXT:    th.vnsrl.vx v8, v10, zero
; CHECK-NEXT:    ret
  %result = call <vscale x 8 x i8> @llvm.riscv.th.vlxe.nxv8i8.nxv8i64(<vscale x 8 x i8> poison, ptr %base, <vscale x 8 x i64> %index, i64 %vl)
  ret <vscale x 8 x i8> %result
}

declare <vscale x 8 x i8> @llvm.riscv.th.vlxe.nxv8i8.nxv8i64(<vscale x 8 x i8>, ptr, <vscale x 8 x i64>, i64)

define <vscale x 8 x i8> @load_i8_index64_masked(ptr %base, <vscale x 8 x i64> %index, <vscale x 8 x i8> %data, <vscale x 8 x i1> %mask, i64 %vl) {
; CHECK-LABEL: load_i8_index64_masked:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; CHECK-NEXT:    th.vwcvtu.x.x.v v18, v16
; CHECK-NEXT:    th.vsetvli zero, zero, e16, m2, d1
; CHECK-NEXT:    th.vwcvtu.x.x.v v20, v18
; CHECK-NEXT:    th.vsetvli zero, zero, e32, m4, d1
; CHECK-NEXT:    th.vwcvtu.x.x.v v24, v20
; CHECK-NEXT:    th.vsetvli zero, zero, e64, m8, d1
; CHECK-NEXT:    th.vlxbu.v v24, (a0), v8, v0.t
; CHECK-NEXT:    th.vsetvli zero, zero, e32, m4, d1
; CHECK-NEXT:    th.vnsrl.vx v8, v24, zero
; CHECK-NEXT:    th.vsetvli zero, zero, e16, m2, d1
; CHECK-NEXT:    th.vnsrl.vx v12, v8, zero
; CHECK-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; CHECK-NEXT:    th.vnsrl.vx v16, v12, zero
; CHECK-NEXT:    th.vmv.v.v v8, v16
; CHECK-NEXT:    ret
  %result = call <vscale x 8 x i8> @llvm.riscv.th.vlxe.mask.nxv8i8.nxv8i64(<vscale x 8 x i8> %data, ptr %base, <vscale x 8 x i64> %index, <vscale x 8 x i1> %mask, i64 %vl)
  ret <vscale x 8 x i8> %result
}

declare <vscale x 8 x i8> @llvm.riscv.th.vlxe.mask.nxv8i8.nxv8i64(<vscale x 8 x i8>, ptr, <vscale x 8 x i64>, <vscale x 8 x i1>, i64)

define void @store_i8_index64(ptr %base, <vscale x 8 x i64> %index, <vscale x 8 x i8> %data, i64 %vl) {
; CHECK-LABEL: store_i8_index64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; CHECK-NEXT:    th.vwcvtu.x.x.v v18, v16
; CHECK-NEXT:    th.vsetvli zero, zero, e16, m2, d1
; CHECK-NEXT:    th.vwcvtu.x.x.v v20, v18
; CHECK-NEXT:    th.vsetvli zero, zero, e32, m4, d1
; CHECK-NEXT:    th.vwcvtu.x.x.v v24, v20
; CHECK-NEXT:    th.vsetvli zero, zero, e64, m8, d1
; CHECK-NEXT:    th.vsxb.v v24, (a0), v8
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.vsxe.nxv8i8.nxv8i64(<vscale x 8 x i8> %data, ptr %base, <vscale x 8 x i64> %index, i64 %vl)
  ret void
}

declare void @llvm.riscv.th.vsxe.nxv8i8.nxv8i64(<vscale x 8 x i8>, ptr, <vscale x 8 x i64>, i64)

define void @store_i8_index64_masked(ptr %base, <vscale x 8 x i64> %index, <vscale x 8 x i8> %data, <vscale x 8 x i1> %mask, i64 %vl) {
; CHECK-LABEL: store_i8_index64_masked:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; CHECK-NEXT:    th.vwcvtu.x.x.v v18, v16
; CHECK-NEXT:    th.vsetvli zero, zero, e16, m2, d1
; CHECK-NEXT:    th.vwcvtu.x.x.v v20, v18
; CHECK-NEXT:    th.vsetvli zero, zero, e32, m4, d1
; CHECK-NEXT:    th.vwcvtu.x.x.v v24, v20
; CHECK-NEXT:    th.vsetvli zero, zero, e64, m8, d1
; CHECK-NEXT:    th.vsxb.v v24, (a0), v8, v0.t
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.vsxe.mask.nxv8i8.nxv8i64(<vscale x 8 x i8> %data, ptr %base, <vscale x 8 x i64> %index, <vscale x 8 x i1> %mask, i64 %vl)
  ret void
}

declare void @llvm.riscv.th.vsxe.mask.nxv8i8.nxv8i64(<vscale x 8 x i8>, ptr, <vscale x 8 x i64>, <vscale x 8 x i1>, i64)

define <vscale x 8 x float> @load_f32_index64(ptr %base, <vscale x 8 x i64> %index, i64 %vl) {
; CHECK-LABEL: load_f32_index64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.vsetvli zero, a1, e64, m8, d1
; CHECK-NEXT:    th.vlxwu.v v16, (a0), v8
; CHECK-NEXT:    th.vsetvli zero, zero, e32, m4, d1
; CHECK-NEXT:    th.vnsrl.vx v8, v16, zero
; CHECK-NEXT:    ret
  %result = call <vscale x 8 x float> @llvm.riscv.th.vlxe.nxv8f32.nxv8i64(<vscale x 8 x float> poison, ptr %base, <vscale x 8 x i64> %index, i64 %vl)
  ret <vscale x 8 x float> %result
}

declare <vscale x 8 x float> @llvm.riscv.th.vlxe.nxv8f32.nxv8i64(<vscale x 8 x float>, ptr, <vscale x 8 x i64>, i64)

define <vscale x 8 x float> @load_f32_index64_masked(ptr %base, <vscale x 8 x i64> %index, <vscale x 8 x float> %data, <vscale x 8 x i1> %mask, i64 %vl) {
; CHECK-LABEL: load_f32_index64_masked:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.vsetvli zero, a1, e32, m4, d1
; CHECK-NEXT:    th.vwcvtu.x.x.v v24, v16
; CHECK-NEXT:    th.vsetvli zero, zero, e64, m8, d1
; CHECK-NEXT:    th.vlxwu.v v24, (a0), v8, v0.t
; CHECK-NEXT:    th.vsetvli zero, zero, e32, m4, d1
; CHECK-NEXT:    th.vnsrl.vx v16, v24, zero
; CHECK-NEXT:    th.vmv.v.v v8, v16
; CHECK-NEXT:    ret
  %result = call <vscale x 8 x float> @llvm.riscv.th.vlxe.mask.nxv8f32.nxv8i64(<vscale x 8 x float> %data, ptr %base, <vscale x 8 x i64> %index, <vscale x 8 x i1> %mask, i64 %vl)
  ret <vscale x 8 x float> %result
}

declare <vscale x 8 x float> @llvm.riscv.th.vlxe.mask.nxv8f32.nxv8i64(<vscale x 8 x float>, ptr, <vscale x 8 x i64>, <vscale x 8 x i1>, i64)

define void @store_f32_index64(ptr %base, <vscale x 8 x i64> %index, <vscale x 8 x float> %data, i64 %vl) {
; CHECK-LABEL: store_f32_index64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.vsetvli zero, a1, e32, m4, d1
; CHECK-NEXT:    th.vwcvtu.x.x.v v24, v16
; CHECK-NEXT:    th.vsetvli zero, zero, e64, m8, d1
; CHECK-NEXT:    th.vsxw.v v24, (a0), v8
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.vsxe.nxv8f32.nxv8i64(<vscale x 8 x float> %data, ptr %base, <vscale x 8 x i64> %index, i64 %vl)
  ret void
}

declare void @llvm.riscv.th.vsxe.nxv8f32.nxv8i64(<vscale x 8 x float>, ptr, <vscale x 8 x i64>, i64)

define void @store_f32_index64_masked(ptr %base, <vscale x 8 x i64> %index, <vscale x 8 x float> %data, <vscale x 8 x i1> %mask, i64 %vl) {
; CHECK-LABEL: store_f32_index64_masked:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.vsetvli zero, a1, e32, m4, d1
; CHECK-NEXT:    th.vwcvtu.x.x.v v24, v16
; CHECK-NEXT:    th.vsetvli zero, zero, e64, m8, d1
; CHECK-NEXT:    th.vsxw.v v24, (a0), v8, v0.t
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.vsxe.mask.nxv8f32.nxv8i64(<vscale x 8 x float> %data, ptr %base, <vscale x 8 x i64> %index, <vscale x 8 x i1> %mask, i64 %vl)
  ret void
}

declare void @llvm.riscv.th.vsxe.mask.nxv8f32.nxv8i64(<vscale x 8 x float>, ptr, <vscale x 8 x i64>, <vscale x 8 x i1>, i64)
